### ISSUE TITLE
remove MW comments file

### ISSUE THREAD

**Issue by mikewessel** [tbep-tech/tbep-tech.github.io#1]
Hey guys - can you remove that file and those comments in subsequent versions of the code. The purpose of that file was really just notes for myself and for initial discussions with the team as we got started on implementing changes to the code. The comments were not something i expected to carry forward into subsequent versions of the code.

**Comment by fawda123** [comment]
We are planning on taking the contents of that file and writing several functions to include in the [tbeptools ](https://github.com/tbep-tech/tbeptools) repo.  Everything will be reworked as we move forward.  Unless you want it down immediately, I'd like to leave it up so we can use it as a working document.

**Comment by mikewessel** [comment]
Ok - if its helpful for you guys in the interim that's fine with me. I just wouldn't want the comments propagated to any public versions.

**Comment by fawda123** [comment]
Of course, the comments are helpful as we get organized but they will not appear in any final products.
