### ISSUE TITLE
Create Travis Cron job to check for current wq file

### ISSUE THREAD

**Issue by fawda123** [tbep-tech/tbep-tech.github.io#2]
See notes on Google drive

**Comment by bbest** [comment]
Hi @bbest ,

I took a stab at getting a cron job setup on our tbep repository yesterday.  I think I’m 99% there but having some issues with the authentication to GitHub for the final push:

![image](https://user-images.githubusercontent.com/2837257/60900239-b6bcf200-a220-11e9-910e-e2be6b41cc3f.png)

I followed the instructions for creating a token and then got an encryption key with the Travis CLI.   You can see the Travis config file here: [.travis.yml](https://github.com/tbep-tech/tbep-tech.github.io/blob/master/.travis.yml)

-- @fawda123

**Comment by bbest** [comment]
Hey Marcus,

I'll have to try with my own credentials, which I can do tomorrow. Meanwhile here are a few links:

- [setup Travis continuous integration (CI) to update daily · Issue #2 · SustainSB/sustainsb.github.io](https://github.com/SustainSB/sustainsb.github.io/issues/2#issuecomment-304355281)
- [GitHub Pages Deployment - Travis CI](https://docs.travis-ci.com/user/deployment/pages/)
- newer way to push to Github for Github pages:
  - [Encryption keys - Travis CI](https://docs.travis-ci.com/user/encryption-keys/)
  - [Cron Jobs - Travis CI](https://docs.travis-ci.com/user/cron-jobs/)

**Comment by bbest** [comment]
Ok, the above commit https://github.com/tbep-tech/tbep-tech.github.io/commit/a75fcdee1ce95629721c94296da4466eb9d2165c seems to have worked as evidenced by the badge now in the repo's README:

![image](https://user-images.githubusercontent.com/2837257/60903004-6eec9980-a225-11e9-8b0b-dff5b76fc390.png)

Here's a couple of things I did that might've made the difference:

1.  I added the personal token to the file `~/.gh-token_tbep-tech` then ran:
    ```bash
    echo GH_TOKEN=`cat ~/.gh-token_tbep-tech` | travis encrypt --add
    ```
    Note how this sets the GH_TOKEN variable which can then be accessed in the [.travis.yml](https://github.com/tbep-tech/tbep-tech.github.io/blob/master/.travis.yml) as $GH_TOKEN.

1. Set the other environmental variables `TRAVIS_REPO_SLUG` and `TRAVIS_BRANCH` used in the `git push` statement:
    ```yaml
    script:
    - git push https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git HEAD:${TRAVIS_BRANCH}
    
    env:
      global:
      - TRAVIS_REPO_SLUG=tbep-tech/tbep-tech.github.io
      - TRAVIS_BRANCH=master
    ```

**Comment by bbest** [comment]
Or on Windows: 

```bash
travis encrypt GH_TOKEN="enteryoursecrettokeninfohere" --add
```

**Comment by fawda123** [comment]
This is still causing headaches... I got the authentication working but now the .Rmd render is getting stuck: 

![image](https://user-images.githubusercontent.com/3086881/60932736-2a3c1f00-a274-11e9-9edf-ff8de803c857.png)

This goes back to the `read_chkdate()` function from tbeptools, specifically this line:  https://github.com/tbep-tech/tbeptools/blob/15cdb9b1fb2d1c2ab0292602c21bb366bd3e9cf2/R/read_chkdate.R#L27

The URL it's trying to access is the TBEP server `ftp://ftp.epchc.org/EPC_ERM_FTP/WQM_Reports/`... works fine locally but seems to get hung on Travis.  Any ideas?

**Comment by fawda123** [comment]
Fixed after making some changes to tbeptools and the DESCRIPTION file here cf2534573775bd8ffc806f40284a7a0d358accb7

I think it was just a matter of requiring RCurl to be installed for R on the Travis machine

**Comment by fawda123** [comment]
Yea this still isn't working.... created a new issue for this #5
