### ISSUE TITLE
Fix color-coding for table

### ISSUE THREAD

**Issue by fawda123** [tbep-tech/tbep-tech.github.io#3]
Color coding needs to be categorical, not as a color ramp, other considerations too related to duration/magnitude

**Comment by bbest** [comment]
Will do, as part of [`show_matrix()`](https://tbep-tech.github.io/tbeptools/reference/show_matrix.html) function

**Comment by fawda123** [comment]
@esherwoo77 what do you mean by duration/magnitude

**Comment by esherwoo77** [comment]
See the appendices in this technical document: https://tbeptech.org/TBEP_TECH_PUBS/2000/TBEP_04_00Chlor-A.pdf @fawda123 @bbest

**Comment by fawda123** [comment]
https://github.com/tbep-tech/tbeptools/commit/7a6393ad82d30624ae10344d1a486c3544970497 generally correct but still some issues with historical data prior to 2007
