### ISSUE TITLE
Fix timeout issues on Travis for getURL

### ISSUE THREAD

**Issue by fawda123** [tbep-tech/tbep-tech.github.io#5]
Travis builds are failing for tbeptools and this repo, traced back to this line: 

https://github.com/tbep-tech/tbeptools/blob/f3c632c206b4f4c1e05c648ae2040c9de843a39c/R/read_chkdate.R#L35

It's a timeout issue for `RCurl::getURL()` when trying to connect to the TBEP FTP.  

I tried some workarounds by increasing the timeout option in `getURL`:  

https://github.com/tbep-tech/tbeptools/commit/fc53039bacc6bfb19aef14677d668c3d8160cd37

I also tried wrapping the call in a `while` loop, which then loops indefinitely until Travis fails after it's own time out of ten minutes:

https://github.com/tbep-tech/tbeptools/commit/5ef6b6b22aff3c8f05f4a56c7dbb43f85d868611

**Comment by bbest** [comment]
Darn, ok, traveling now, will look into this early next week. Thanks @fawda123!

**Comment by fawda123** [comment]
This seems to be working now with some changes to server connection function `getURL()` - I added an argument to change the maximum amount of time to wait before time out and an option to run it in a while loop until the connection is successful.
